---
server:
    install: '1'
    packages: [git]
    timezone: UTC
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: helpling-solid, ip: 192.168.33.99, memory: '1024', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
mongodb:
    install: '1'
sqlite:
    install: '1'
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-sqlite, php5-mongo]
composer:
    install: '1'

